spring.application.name: pf-assignment
spring.profiles.active: local

server:
  port: 8090
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 1000

---
spring.config.activate.on-profile: local

spring:
  sql:
    init:
      mode: always
      data-locations: classpath:db/init-data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
